"""
medical_record.py (schema)
--------------------------
Pydantic schemas for the MedicalRecord entity.
These define the shape of data accepted by the API (input) and
returned by the API (output) — separate from the SQLAlchemy model.

Schemas in this file:
- MedicalRecordBase   : shared fields used by Create and Response
- MedicalRecordCreate : fields required to create a new record (no id, no created_at)
- MedicalRecordResponse : full representation returned by the API
"""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class MedicalRecordBase(BaseModel):
    """
    Fields shared between the Create and Response schemas.
    All fields are optional here because a medical record can be
    created with minimal data and updated later.
    """

    patient_id: int                        # external reference to UserService
    doctor_id: int                         # external reference to UserService
    notes: Optional[str] = None
    blood_type_id: Optional[int] = None   # references blood_type.id (1–8)

    # Field() sets max digits and decimal places to match the DB column DECIMAL(5,2)
    weight: Optional[float] = Field(default=None, ge=0, le=999.99, description="Weight in kilograms")
    height: Optional[float] = Field(default=None, ge=0, le=9.99, description="Height in meters")


class MedicalRecordCreate(MedicalRecordBase):
    """
    Schema for creating a new medical record.
    Inherits all fields from MedicalRecordBase.
    The client must provide at least patient_id.
    id and created_at are excluded — the database generates them.
    """
    pass


class MedicalRecordResponse(MedicalRecordBase):
    """
    Schema for returning a medical record from the API.
    Includes id and created_at which are generated by the database.
    """

    id: int
    created_at: datetime

    class Config:
        # Allows Pydantic to read data from SQLAlchemy model instances
        # (not just plain dictionaries)
        from_attributes = True
