spring.application.name=AppointmentService
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/medly_appointments?zeroDateTimeBehavior=CONVERT_TO_NULL
spring.datasource.username=root
spring.datasource.password=itson
spring.jpa.hibernate.ddl-auto=update